- name: Install Apache
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Apache is running
  service:
    name: apache2
    state: started

- name: Copy website
  template:
    src: website.conf.j2
    dest: /etc/apache2/sites-enabled/website.conf
  notify: Restart Apache
  
    
