- hosts: webservers
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  become: yes

  vars:
    package_name: apache2
    service_name: apache2
    document_root: /var/www/html
    website_name: www.basil.com
    website_list:
      - www.basil.com
      - www.devops.com
      - www.example.com
      - www.test.com 
# vars:

  # package_name: apache2
# Note the to refernce a variable we use "{{package_name}}"
  tasks:
    - name: Apache must be installed
      # apt mudule is used to install apache
      apt:
        name: "{{package_name}}"
        state: latest
        update_cache: yes
        
    - name: Apache service must be running
      # service module is used to start apache
      service:
        name: "{{service_name}}"
        state: started
        enabled: yes

    - name: index.html file should be present on /var/www/html folder of webservers
      # Copy module is used to copy a file from a source to the remote machine
      copy:
          src: /home/ansible/.ansible/index.html
          dest: "{{document_root}}/index.html"
       
    - name: Copy Basil.con website configuration
      template:
        src: /home/ansible/.ansible/website.conf.j2
        dest: /etc/apache2/sites-enabled/website.conf
      notify: Restart Apache
  
  handlers:
    - name: Restart Apache
      service: 
        name: "{{service_name}}"
        state: reloaded
  
